[0.3.8]
Title = "Version 0.3.9"
Description = [ "Fix project description.", "- Project description still refers to setup.py instead of setup.cfg..",]

[0.3.8]
Title = "Version 0.3.8"
Description = [ "Fix project description.", "- Project description still refers to setup.py instead of setup.cfg..",]

[0.3.7]
Title = "Version 0.3.7"
Description = [ "Fix project description.", "- Project description still refers to setup.py instead of setup.cfg..",]

[0.3.6]
Title = "Version 0.3.6"
Description = [ "Implement PackageIt bug fixes.", "- Apply PackageIt bug fixes.",]

[0.3.5]
Title = "Version 0.3.5"
Description = [ "Verify the version string.", "- SemVerIt should only accept version strings in the format n.n.n. Any other string should be rejected with an exception.", "Implement Exception class.",]

[0.3.4]
Title = "Version 0.3.4"
Description = [ "Sync versions.",]

[0.3.3]
Title = "Version 0.3.3"
Description = [ "Apply PackageIt improvements.", "- . ",]

[0.3.2]
Title = "Version 0.3.2"
Description = [ "Apply PackageIt improvements.", "- Added release management to PackageIt. Apply the changes and inspect the results.", "The initial version of a new created project should be 0.0.0 which indicate that it is a virgin project.", "- SemVerIt currently return 0.0.1 for a new project,  Change it to 0.0.0",]

[0.3.1]
Title = "Version 0.3.1"
Description = [ "setup.cfg initialized but not created.", "- When the setup.cfg path is initialized, but the file is not created yet, the version is not read from the setup.cfg file.",]

[0.3.0]
Title = "Version 0.3.0"
Description = [ "Add __str__ dunder.", "- Implement the __str__ dunder.",]

[0.2.0]
Title = "Version 0.2.0"
Description = [ "Enable the ability to initialize the object with a list containing the version i.e. [1, 2, 3] or [\"1\", \"2\", \"3\"].", "Compare (==, <=, <, >=, >, != ) with another SemVerIt object",]

[0.1.1]
Title = "Version 0.1.1"
Description = [ "Add missing parts to setup.cfg and fix semverit.py.", "Add missing sections and options to setup.cfg after discontinuation of setup.py.", "Fix comments in semverit.get_from_setup_cfg.",]

[0.1.0]
Title = "Version 0.1.0"
Description = [ "Discontinue the usage of setup.py.", "Make configuration changes.", "Discontinue the usage of setup.py to exclusive usage of setup.cfg.", "Adapt tests.",]

[0.0.5]
Title = "Version 0.0.5"
Description = [ "Change initial project setup parameters.", "Updated project description.", "Introduce the .packageit config structure.", "Change the github workflow release.yaml to point to production PyPI.", "Add logging test", "Changed version in setup.py.",]

[0.0.4]
Title = "Version 0.0.4"
Description = [ "Adapt examples", "Import statement was incorrect.", "Changed version in setup.py.",]

[0.0.3]
Title = "Version 0.0.3"
Description = [ "Streamlining for PackageIt", "Make log_name private.", "Improve Example1.", "Improve Example2.", "Improve Example3.", "Make working_dir a fixture",]

[0.0.2]
Title = "Version 0.0.2"
Description = [ "Experimenting with Git", "Experimented with ome of the project configuration changes that are not relevant to SemVerIt.", "Coding is the same as 0.0.1.",]

[0.0.1]
Title = "Version 0.0.1"
Description = [ "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
