[0.0.1]
Version = '0.0.1'
Title = 'Creation of the project'
Description = ['List all the changes to the project here.',
               'Changes listed here will be in the release notes under the above heading.']
FileChanges = [['filename01.py','Insert change description here.'],
               ['filename02.txt','Insert change description here.']]

[0.0.2]
Version = '0.0.2'
Title = 'Experimenting with Git'
Description = ['Experimented with ome of the project configuration changes that are not relevant to SemVerIt.',
               'Coding is the same as 0.0.1.']
FileChanges = []

[0.0.3]
Version = '0.0.3'
Title = 'Streamlining for PackageIt'
Description = ['Make log_name private.',
               'Improve Example1.',
               'Improve Example2.',
               'Improve Example3.',
               'Make working_dir a fixture']
FileChanges = []

[0.0.4]
Version = '0.0.4'
Title = 'Adapt examples'
Description = ['Import statment was incorrect.',
               'Changed version in setup.py.']
FileChanges = []

[0.0.5]
Version = '0.0.5'
Title = 'Change initial project setup parameters.'
Description = ['Updated project description.',
               'Introduce the .packageit config structure.',
               'Change the github workflow release.yaml to point to production PyPI.',
               'Add logging test',
               'Changed version in setup.py.',]
FileChanges = []

[0.0.7]
Version = '0.0.7'
Title = 'Further non-impact experimental changes.'
Description = ['Unknown']
FileChanges = []

[0.1.0]
Version = '0.1.0'
Title = 'Discontinue the usage of setup.py.'
Description = ['Make configuration changes.',
               'Discontinue the usage of setup.py to exclusive usage of setup.cfg.',
               'Adapt tests.']
FileChanges = []
